name: bikerr_partner_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  animated_splash_screen: ^1.3.0
  another_flushbar: ^1.12.29
  connectivity_plus: ^4.0.2
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  flutter_launcher_icons: null
  flutter_screenutil: ^5.9.0
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.1.6
  geolocator: ^10.0.0
  get: ^4.6.5
  hexcolor: ^3.0.1
  http: ^1.1.0
  intl: 0.17.0
  mapmyindia_gl: ^0.3.2
  shared_preferences: ^2.2.1
  web_socket_channel: ^2.4.0
  sqflite: ^2.2.8+4
  permission_handler: ^11.0.0
  image_picker: ^1.0.4
  rename: ^2.1.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/1024.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 300
